import * as React from "react";
import * as SliderPrimitive from "@radix-ui/react-slider";

import { cn } from "../../lib/utils.js";

// Generated by v0 to allow for veritical orientation working properly.
const Slider = React.forwardRef<
  React.ElementRef<typeof SliderPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root>
>(({ className, ...props }, ref) => (
  <SliderPrimitive.Root
    ref={ref}
    orientation="vertical" // Set orientation to vertical
    className={cn("relative flex h-full touch-none select-none flex-col-reverse items-center", className)}
    {...props}
  >
    <SliderPrimitive.Track className="relative w-2 h-full overflow-hidden bg-gray-500 rounded-full grow">
      <SliderPrimitive.Range className="absolute bottom-0 w-full bg-primary" />
    </SliderPrimitive.Track>
    <SliderPrimitive.Thumb className="block w-5 h-5 transition-colors bg-white border-2 rounded-full border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50" />
  </SliderPrimitive.Root>
));
Slider.displayName = SliderPrimitive.Root.displayName;

export { Slider }

